export const projectsData = [
  {
    id: 1,
    image: "/placeholder.svg?height=300&width=600",
    title: "Residencial Los Álamos",
    location: "Madrid, España",
    returnRate: 8.5,
    duration: "12 meses",
    progress: 75,
    status: "Financiando",
    description:
      "Proyecto residencial de lujo ubicado en una de las zonas más exclusivas de Madrid. Incluye 24 apartamentos con acabados de primera calidad.",
    minInvestment: "5.000€",
    totalFunding: "1.200.000€",
  },
  {
    id: 2,
    image: "/placeholder.svg?height=300&width=600",
    title: "Edificio Meridiano",
    location: "Barcelona, España",
    returnRate: 9.2,
    duration: "18 meses",
    progress: 45,
    status: "Financiando",
    description:
      "Desarrollo de uso mixto que combina espacios comerciales y residenciales en el corazón de Barcelona.",
    minInvestment: "10.000€",
    totalFunding: "2.500.000€",
  },
  {
    id: 3,
    image: "/placeholder.svg?height=300&width=600",
    title: "Torres del Parque",
    location: "Valencia, España",
    returnRate: 7.8,
    duration: "24 meses",
    progress: 90,
    status: "Casi completo",
    description:
      "Complejo residencial con vistas al parque central de Valencia, diseñado con los más altos estándares de sostenibilidad.",
    minInvestment: "7.500€",
    totalFunding: "1.800.000€",
  },
  {
    id: 4,
    image: "/placeholder.svg?height=300&width=600",
    title: "Residencial Marina",
    location: "Málaga, España",
    returnRate: 8.8,
    duration: "15 meses",
    progress: 30,
    status: "Financiando",
    description:
      "Exclusivo desarrollo frente al mar con acceso directo a la playa y amenidades de primer nivel.",
    minInvestment: "15.000€",
    totalFunding: "3.000.000€",
  },
  {
    id: 5,
    image: "/placeholder.svg?height=300&width=600",
    title: "Residencial Los Álamos",
    location: "Madrid, España",
    returnRate: 8.5,
    duration: "12 meses",
    progress: 75,
    status: "Financiando",
    description:
      "Proyecto residencial de lujo ubicado en una de las zonas más exclusivas de Madrid. Incluye 24 apartamentos con acabados de primera calidad.",
    minInvestment: "5.000€",
    totalFunding: "1.200.000€",
  },
  {
    id: 6,
    image: "/placeholder.svg?height=300&width=600",
    title: "Edificio Meridiano",
    location: "Barcelona, España",
    returnRate: 9.2,
    duration: "18 meses",
    progress: 45,
    status: "Financiando",
    description:
      "Desarrollo de uso mixto que combina espacios comerciales y residenciales en el corazón de Barcelona.",
    minInvestment: "10.000€",
    totalFunding: "2.500.000€",
  },
  {
    id: 7,
    image: "/placeholder.svg?height=300&width=600",
    title: "Torres del Parque",
    location: "Valencia, España",
    returnRate: 7.8,
    duration: "24 meses",
    progress: 90,
    status: "Casi completo",
    description:
      "Complejo residencial con vistas al parque central de Valencia, diseñado con los más altos estándares de sostenibilidad.",
    minInvestment: "7.500€",
    totalFunding: "1.800.000€",
  },
  {
    id: 8,
    image: "/placeholder.svg?height=300&width=600",
    title: "Residencial Marina",
    location: "Málaga, España",
    returnRate: 8.8,
    duration: "15 meses",
    progress: 30,
    status: "Financiando",
    description:
      "Exclusivo desarrollo frente al mar con acceso directo a la playa y amenidades de primer nivel.",
    minInvestment: "15.000€",
    totalFunding: "3.000.000€",
  },
];
